<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Journal Ledger | Maju Bersama ERP</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
</head>
<body x-data="journalLedger()" class="min-h-screen bg-slate-100 text-slate-900 antialiased">
    <header class="border-b border-slate-800 bg-slate-950 text-white">
        <div class="mx-auto flex max-w-7xl items-center justify-between px-6 py-5 lg:px-8">
            <div>
                <p class="text-xs font-semibold uppercase tracking-[0.24em] text-amber-400">Maju Bersama ERP</p>
                <h1 class="mt-1 text-2xl font-bold tracking-tight">General Ledger</h1>
            </div>
            <div class="flex items-center gap-4">
                <nav class="hidden items-center gap-4 text-sm text-slate-300 md:flex">
                    <a href="/pos" class="hover:text-white">POS</a>
                    <a href="/inventory" class="hover:text-white">Inventory</a>
                    <a href="/reports/journal" class="font-semibold text-white">Ledger</a>
                </nav>
                <div class="rounded-full border border-sky-400/30 bg-sky-400/10 px-3 py-1 text-xs font-medium text-sky-200">
                    {{ $headers->count() }} transactions
                </div>
                <form method="POST" action="/logout" class="hidden sm:block">
                    @csrf
                    <button type="submit" class="text-sm text-slate-300 hover:text-white">Logout</button>
                </form>
            </div>
        </div>
    </header>

    <main class="mx-auto max-w-7xl space-y-8 px-6 py-10 lg:px-8">
        <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
            <div>
                <p class="text-sm font-medium text-amber-600">Financial reporting</p>
                <h2 class="mt-2 text-3xl font-bold tracking-tight text-slate-950">Journal ledger</h2>
                <p class="mt-2 text-slate-500">Every debit and credit generated by ERP transactions.</p>
            </div>
            <div class="flex flex-col gap-3 sm:items-end">
                <div class="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-right">
                    <p class="text-xs font-semibold uppercase tracking-wider text-emerald-700">Ledger integrity</p>
                    <p class="mt-1 text-sm font-bold text-emerald-800">Double-entry review</p>
                </div>
                <input x-model="query" type="search" placeholder="Search reference or description..." class="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm outline-none ring-sky-500 placeholder:text-slate-400 focus:ring-2">
            </div>
        </div>

        <div class="space-y-6">
            @forelse ($headers as $header)
                @php
                    $totalDebit = $header->journalLines->sum(fn ($line) => (float) $line->debit);
                    $totalCredit = $header->journalLines->sum(fn ($line) => (float) $line->credit);
                    $isBalanced = abs($totalDebit - $totalCredit) < 0.005;
                @endphp
                <section x-show="matches('{{ strtolower($header->reference_number.' '.$header->description) }}')" class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
                    <div class="flex flex-col gap-5 border-b border-slate-200 px-6 py-5 lg:flex-row lg:items-center lg:justify-between">
                        <div class="flex items-start gap-4">
                            <div class="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-slate-900 text-sm font-bold text-amber-400">JV</div>
                            <div>
                                <div class="flex flex-wrap items-center gap-3">
                                    <h3 class="font-mono text-sm font-bold text-sky-700">{{ $header->reference_number }}</h3>
                                    <span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-medium text-slate-600">#{{ $header->id }}</span>
                                </div>
                                <p class="mt-2 text-lg font-semibold text-slate-950">{{ $header->description }}</p>
                                <p class="mt-1 text-sm text-slate-500">
                                    {{ $header->transaction_date->format('d M Y') }}
                                    <span class="mx-1 text-slate-300">&middot;</span>
                                    {{ $header->user?->name ?? 'System' }}
                                </p>
                            </div>
                        </div>
                        <span class="inline-flex w-fit items-center gap-2 rounded-full px-3 py-1.5 text-xs font-bold {{ $isBalanced ? 'bg-emerald-50 text-emerald-700' : 'bg-rose-50 text-rose-700' }}">
                            <span class="h-2 w-2 rounded-full {{ $isBalanced ? 'bg-emerald-500' : 'bg-rose-500' }}"></span>
                            {{ $isBalanced ? 'Balanced' : 'Out of balance' }}
                        </span>
                    </div>

                    <div class="overflow-x-auto">
                        <table class="min-w-full divide-y divide-slate-200">
                            <thead class="bg-slate-50">
                                <tr>
                                    <th class="px-6 py-3 text-left text-xs font-semibold uppercase tracking-wider text-slate-500">Account</th>
                                    <th class="px-6 py-3 text-left text-xs font-semibold uppercase tracking-wider text-slate-500">Account name</th>
                                    <th class="px-6 py-3 text-right text-xs font-semibold uppercase tracking-wider text-slate-500">Debit</th>
                                    <th class="px-6 py-3 text-right text-xs font-semibold uppercase tracking-wider text-slate-500">Credit</th>
                                </tr>
                            </thead>
                            <tbody class="divide-y divide-slate-100">
                                @foreach ($header->journalLines as $line)
                                    <tr class="hover:bg-slate-50">
                                        <td class="whitespace-nowrap px-6 py-4 font-mono text-sm font-semibold text-sky-700">{{ $line->chartOfAccount?->code ?? '—' }}</td>
                                        <td class="px-6 py-4 text-sm text-slate-700">{{ $line->chartOfAccount?->name ?? 'Unknown account' }}<span class="ml-2 text-xs text-slate-400">{{ $line->memo }}</span></td>
                                        <td class="whitespace-nowrap px-6 py-4 text-right text-sm {{ (float) $line->debit > 0 ? 'font-semibold text-slate-900' : 'text-slate-300' }}">{{ (float) $line->debit > 0 ? 'Rp '.number_format((float) $line->debit, 0, ',', '.') : '—' }}</td>
                                        <td class="whitespace-nowrap px-6 py-4 text-right text-sm {{ (float) $line->credit > 0 ? 'font-semibold text-slate-900' : 'text-slate-300' }}">{{ (float) $line->credit > 0 ? 'Rp '.number_format((float) $line->credit, 0, ',', '.') : '—' }}</td>
                                    </tr>
                                @endforeach
                            </tbody>
                            <tfoot class="border-t-2 border-slate-200 bg-slate-50">
                                <tr>
                                    <th colspan="2" class="px-6 py-4 text-left text-xs font-bold uppercase tracking-wider text-slate-600">Transaction totals</th>
                                    <th class="px-6 py-4 text-right text-sm font-bold text-slate-950">Rp {{ number_format($totalDebit, 0, ',', '.') }}</th>
                                    <th class="px-6 py-4 text-right text-sm font-bold text-slate-950">Rp {{ number_format($totalCredit, 0, ',', '.') }}</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </section>
            @empty
                <section class="rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-16 text-center">
                    <p class="font-semibold text-slate-800">No journal transactions yet</p>
                    <p class="mt-2 text-sm text-slate-500">Complete a POS sale to see its automated double-entry journal here.</p>
                </section>
            @endforelse
        </div>
    </main>
    <script>
        function journalLedger() {
            return {
                query: '',
                matches(value) {
                    return !this.query.trim() || value.includes(this.query.toLowerCase().trim());
                },
            };
        }
    </script>
</body>
</html>